# Generated by Django 4.2 on 2025-04-04 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=10, null=True)),
                ('crm', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('espe', models.CharField(choices=[('CIRURGIAO', 'Cirurgiao'), ('ODONTO', 'Odonto'), ('PEDIATRA', 'Pediatra')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(blank=True, max_length=10, null=True)),
                ('data', models.DateTimeField()),
                ('status', models.CharField(choices=[('AGENDADO', 'agendado'), ('REALIZADO', 'realizado'), ('CANCELADO', 'cancelado')], max_length=10)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.medico')),
            ],
        ),
    ]
