# Generated by Django 4.2 on 2025-04-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_alter_medico_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='nome',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
